# Generated by Django 2.2.2 on 2019-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Reviewed')], db_index=True, default=1, max_length=2, verbose_name='Статус'),
        ),
    ]
