# Generated by Django 2.2.2 on 2019-06-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0002_auto_20190622_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='message_type',
            field=models.CharField(db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='mqerror',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Reviewed')], db_index=True, default=1, verbose_name='Статус'),
        ),
    ]
