# Generated by Django 2.2.2 on 2019-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0003_auto_20190622_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='message_type',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
    ]
