# Generated by Django 2.2.2 on 2019-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0004_auto_20190622_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqMessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of message type', max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Message Type',
                'verbose_name_plural': 'Message Types',
            },
        ),
    ]
