# Generated by Django 2.2.2 on 2019-07-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0006_auto_20190715_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='message_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mq_errors', to='mq.MqMessageType', verbose_name='Message Type'),
        ),
    ]
