# Generated by Django 2.2.2 on 2020-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0007_auto_20190718_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='queue_message',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Повідомлення черги'),
        ),
    ]
