# Generated by Django 2.2.2 on 2020-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mq', '0008_auto_20200315_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqerror',
            name='queue_message',
            field=models.TextField(blank=True, null=True, verbose_name='Повідомлення черги'),
        ),
    ]
